[package]
description = "QuorumScope component"
repository = "https://github.com/QuorumScope/quorumscope-engine"
authors = ["zeepearl56"]
name = "quorumscope-report"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
quorumscope-domain = { path = "../quorumscope-domain", version = "0.1.0" }
thiserror.workspace = true
tokio.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["full"] }
uuid = { workspace = true }
