[package]
description = "QuorumScope component"
repository = "https://github.com/QuorumScope/quorumscope-engine"
authors = ["zeepearl56"]
name = "quorumscope-rpc"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
tokio = { workspace = true, features = ["full"] }
reqwest = { workspace = true, features = ["json"] }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
url.workspace = true
