[package]

description = "QuorumScope component"
repository = "https://github.com/QuorumScope/quorumscope-engine"
authors = ["zeepearl56"]
name = "quorumscope-api"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
sqlx.workspace = true
uuid.workspace = true
tokio = { workspace = true, features = ["full"] }
axum.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
chrono.workspace = true
hex.workspace = true
utoipa = { workspace = true, features = ["uuid"] }

[lib]

[dev-dependencies]
tower = { version = "0.5", features = ["util"] }
