[package]
description = "QuorumScope component"
repository = "https://github.com/QuorumScope/quorumscope-engine"
authors = ["zeepearl56"]
name = "quorumscope-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
indicatif = "0.17.8"
anyhow.workspace = true
clap = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["full"] }
tracing.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter"] }
quorumscope-api = { path = "../quorumscope-api", version = "0.1.0" }
quorumscope-indexer = { path = "../quorumscope-indexer", version = "0.1.0" }
quorumscope-storage = { path = "../quorumscope-storage", version = "0.1.0" }
