[package]
description = "QuorumScope component"
repository = "https://github.com/QuorumScope/quorumscope-engine"
authors = ["zeepearl56"]
name = "quorumscope-xdr"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
stellar-xdr.workspace = true
base64.workspace = true
sha2.workspace = true
thiserror.workspace = true
quorumscope-domain = { path = "../quorumscope-domain", version = "0.1.0" }
serde_json.workspace = true
hex.workspace = true
